---
deployment:
  tasks:
    - export DEPLOY_PATH=/home/ricoz/ricoz.in
    - export NODE_VERSION=16 # or any version compatible with your app
    - /opt/cpanel/ea-nodejs16/bin/npm install
    - /opt/cpanel/ea-nodejs16/bin/npm run build
    - rsync -av --delete build/ $DEPLOY_PATH/public_html/

commands:
  pre:
    - echo "Pre-deployment steps"
  post:
    - echo "Post-deployment steps"
